/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// JobCommitStatusWhenSpecApplyConfiguration represents a declarative configuration of the JobCommitStatusWhenSpec type for use
// with apply.
//
// JobCommitStatusWhenSpec holds the expression used to evaluate a finished Job.
type JobCommitStatusWhenSpecApplyConfiguration struct {
	// Expression is an expr expression (github.com/expr-lang/expr) evaluated against the finished Job.
	// It must return a boolean: true means success, false means failure.
	//
	// Available variables:
	// - Job (batchv1.Job): the finished child Job object
	//
	// A reasonable documented default for most use cases is a zero exit code on the main container,
	// expressed as:
	//
	// "Job.status.succeeded >= 1"
	//
	// Users running multi-completion Jobs, or who need to distinguish a nonzero exit code (Failed) from
	// an infrastructure problem such as ImagePullBackOff (Error, the way Argo Workflows does), can inspect
	// Job.status (and, in the future, pod/container statuses) in the expression.
	Expression *string `json:"expression,omitempty"`
}

// JobCommitStatusWhenSpecApplyConfiguration constructs a declarative configuration of the JobCommitStatusWhenSpec type for use with
// apply.
func JobCommitStatusWhenSpec() *JobCommitStatusWhenSpecApplyConfiguration {
	return &JobCommitStatusWhenSpecApplyConfiguration{}
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *JobCommitStatusWhenSpecApplyConfiguration) WithExpression(value string) *JobCommitStatusWhenSpecApplyConfiguration {
	b.Expression = &value
	return b
}
