/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	internal "github.com/argoproj-labs/gitops-promoter/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// JobCommitStatusApplyConfiguration represents a declarative configuration of the JobCommitStatus type for use
// with apply.
//
// JobCommitStatus is the Schema for the jobcommitstatuses API.
//
// It gates promotions on in-cluster batch work: for each applicable environment (resolved from the
// referenced PromotionStrategy), the controller creates a Job from jobTemplate for the relevant hydrated
// SHA (per reportOn), observes it, and reflects the result into a CommitStatus.
type JobCommitStatusApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	// metadata is a standard object metadata
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec defines the desired state of JobCommitStatus
	Spec *JobCommitStatusSpecApplyConfiguration `json:"spec,omitempty"`
	// status defines the observed state of JobCommitStatus
	Status *JobCommitStatusStatusApplyConfiguration `json:"status,omitempty"`
}

// JobCommitStatus constructs a declarative configuration of the JobCommitStatus type for use with
// apply.
func JobCommitStatus(name, namespace string) *JobCommitStatusApplyConfiguration {
	b := &JobCommitStatusApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("JobCommitStatus")
	b.WithAPIVersion("promoter.argoproj.io/v1alpha1")
	return b
}

// ExtractJobCommitStatusFrom extracts the applied configuration owned by fieldManager from
// jobCommitStatus for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// jobCommitStatus must be a unmodified JobCommitStatus API object that was retrieved from the Kubernetes API.
// ExtractJobCommitStatusFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractJobCommitStatusFrom(jobCommitStatus *apiv1alpha1.JobCommitStatus, fieldManager string, subresource string) (*JobCommitStatusApplyConfiguration, error) {
	b := &JobCommitStatusApplyConfiguration{}
	err := managedfields.ExtractInto(jobCommitStatus, internal.Parser().Type("com.github.argoproj-labs.gitops-promoter.api.v1alpha1.JobCommitStatus"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(jobCommitStatus.Name)
	b.WithNamespace(jobCommitStatus.Namespace)

	b.WithKind("JobCommitStatus")
	b.WithAPIVersion("promoter.argoproj.io/v1alpha1")
	return b, nil
}

// ExtractJobCommitStatus extracts the applied configuration owned by fieldManager from
// jobCommitStatus. If no managedFields are found in jobCommitStatus for fieldManager, a
// JobCommitStatusApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// jobCommitStatus must be a unmodified JobCommitStatus API object that was retrieved from the Kubernetes API.
// ExtractJobCommitStatus provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractJobCommitStatus(jobCommitStatus *apiv1alpha1.JobCommitStatus, fieldManager string) (*JobCommitStatusApplyConfiguration, error) {
	return ExtractJobCommitStatusFrom(jobCommitStatus, fieldManager, "")
}

// ExtractJobCommitStatusStatus extracts the applied configuration owned by fieldManager from
// jobCommitStatus for the status subresource.
func ExtractJobCommitStatusStatus(jobCommitStatus *apiv1alpha1.JobCommitStatus, fieldManager string) (*JobCommitStatusApplyConfiguration, error) {
	return ExtractJobCommitStatusFrom(jobCommitStatus, fieldManager, "status")
}

func (b JobCommitStatusApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithKind(value string) *JobCommitStatusApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithAPIVersion(value string) *JobCommitStatusApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithName(value string) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithGenerateName(value string) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithNamespace(value string) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithUID(value types.UID) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithResourceVersion(value string) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithGeneration(value int64) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithCreationTimestamp(value metav1.Time) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *JobCommitStatusApplyConfiguration) WithLabels(entries map[string]string) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *JobCommitStatusApplyConfiguration) WithAnnotations(entries map[string]string) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *JobCommitStatusApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *JobCommitStatusApplyConfiguration) WithFinalizers(values ...string) *JobCommitStatusApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *JobCommitStatusApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithSpec(value *JobCommitStatusSpecApplyConfiguration) *JobCommitStatusApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *JobCommitStatusApplyConfiguration) WithStatus(value *JobCommitStatusStatusApplyConfiguration) *JobCommitStatusApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *JobCommitStatusApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *JobCommitStatusApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *JobCommitStatusApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *JobCommitStatusApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
