/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// JobCommitStatusConfigurationApplyConfiguration represents a declarative configuration of the JobCommitStatusConfiguration type for use
// with apply.
//
// JobCommitStatusConfiguration defines the configuration for the JobCommitStatus controller.
//
// This configuration controls how the JobCommitStatus controller processes reconciliation
// requests, including requeue intervals, concurrency limits, and rate limiting behavior.
type JobCommitStatusConfigurationApplyConfiguration struct {
	// WorkQueue contains the work queue configuration for the JobCommitStatus controller.
	// This includes requeue duration, maximum concurrent reconciles, and rate limiter settings.
	WorkQueue *WorkQueueApplyConfiguration `json:"workQueue,omitempty"`
}

// JobCommitStatusConfigurationApplyConfiguration constructs a declarative configuration of the JobCommitStatusConfiguration type for use with
// apply.
func JobCommitStatusConfiguration() *JobCommitStatusConfigurationApplyConfiguration {
	return &JobCommitStatusConfigurationApplyConfiguration{}
}

// WithWorkQueue sets the WorkQueue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkQueue field is set to the value of the last call.
func (b *JobCommitStatusConfigurationApplyConfiguration) WithWorkQueue(value *WorkQueueApplyConfiguration) *JobCommitStatusConfigurationApplyConfiguration {
	b.WorkQueue = value
	return b
}
