/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/batch/v1"
)

// JobCommitStatusSpecApplyConfiguration represents a declarative configuration of the JobCommitStatusSpec type for use
// with apply.
//
// JobCommitStatusSpec defines the desired state of JobCommitStatus.
//
// Applicable environments are NOT enumerated on this resource. Instead, the controller resolves
// them from the referenced PromotionStrategy the same way GitCommitStatus and WebRequestCommitStatus
// do: an environment is applicable when Key matches an entry in PromotionStrategy.Spec.ProposedCommitStatuses
// or Environment.ProposedCommitStatuses (reportOn=proposed), or PromotionStrategy.Spec.ActiveCommitStatuses
// or Environment.ActiveCommitStatuses (reportOn=active). The PromotionStrategy remains the single
// authoritative source for "which environments does this gate apply to".
type JobCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef is a reference to the promotion strategy that this commit status applies to.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Key is the gate name referenced in the PromotionStrategy's proposedCommitStatuses or activeCommitStatuses.
	// It is used as the commit status key and in status messages.
	// Must be lowercase alphanumeric with hyphens, 1–63 characters (pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$).
	Key *string `json:"key,omitempty"`
	// ReportOn specifies which commit SHA the Job is run against and the CommitStatus is reported on.
	// - "proposed" (default): the controller (re)creates the Job whenever the proposed hydrated SHA
	// changes for an applicable environment. Use this for pre-promotion gates (tests, evals, migrations
	// dry-runs) that must pass before the change is promoted.
	// - "active": the controller (re)creates the Job whenever the active hydrated SHA changes. Use this
	// for post-promotion checks that re-validate the environment after a promotion has landed.
	ReportOn *string `json:"reportOn,omitempty"`
	// DescriptionTemplate is the human-readable commit status description shown in the SCM provider
	// (GitHub, GitLab, etc.). Uses Go templates (text/template plus Sprig functions, same engine as
	// the other built-in gates).
	//
	// Template variables (mirrors WebRequestCommitStatus's promotionstrategy-context variable set).
	// Fields are accessed by their Go struct names (capitalized), not JSON/YAML keys, since these are
	// Go templates rendered directly against the Go objects — for example {{ .Job.Status.Succeeded }},
	// not {{ .Job.status.succeeded }} (the latter is only valid in spec.success.when.expression, which
	// evaluates a separate JSON-shaped copy of the Job; see JobCommitStatusWhenSpec):
	// - {{ .Branch }}: the environment branch the Job was created for
	// - {{ .PromotionStrategy }}: the full PromotionStrategy object (spec and status)
	// - {{ .JobCommitStatus }}: the full JobCommitStatus object (snapshot from the start of this reconcile)
	// - {{ .NamespaceMetadata.Labels }} / {{ .NamespaceMetadata.Annotations }}: labels/annotations of the namespace
	// - {{ .Job }}: the child Job once it has reached a terminal phase (success or failure); nil while
	// still running, so the description can distinguish "no result yet" from "here's what happened"
	// and surface details such as {{ .Job.Status.Conditions }} or a container's termination message.
	//
	// If not specified (the default), the description is generated automatically from the Job's own
	// terminal condition (or "Job <name> is running" while pending) — this is a reasonable default for
	// most use cases, so DescriptionTemplate is only needed to customize the wording or surface extra
	// detail from the Job. A template that fails to render is reported via a Warning event and the
	// Ready condition; the automatic description is used for that reconcile so a broken template never
	// blocks or changes a promotion decision.
	DescriptionTemplate *string `json:"descriptionTemplate,omitempty"`
	// Success defines how to decide success/failure from the finished child Job.
	Success *JobCommitStatusSuccessSpecApplyConfiguration `json:"success,omitempty"`
	// JobTemplate is a standard batch/v1 Job template, embedded verbatim. The controller does not inject
	// defaults into the Job spec itself — native Job mechanics carry their own weight:
	// backoffLimit            -> retry semantics
	// activeDeadlineSeconds   -> timeout
	// ttlSecondsAfterFinished -> cleanup (a reasonable suggestion is 24h; not defaulted by the controller)
	//
	// Templating (Go templates, same variables as DescriptionTemplate, with Job always nil since the
	// Job doesn't exist yet) is supported ONLY in the VALUES of jobTemplate.metadata.labels and
	// jobTemplate.metadata.annotations — keys are never templated, and the rest of the Job spec
	// (including jobTemplate.spec.template, the Pod template) is used as-is. A template value that
	// fails to render fails Job creation for that environment (reported the same way as any other
	// creation failure: a Warning event and the Ready condition; the standard rate-limited retry
	// applies). Because a raw environment branch (e.g. "environment/production") contains "/" and is
	// not a valid Kubernetes label value, sanitize it first if you use {{ .Branch }} in a label value,
	// for example {{ .Branch | replace "/" "-" }}; annotation values have no such restriction.
	//
	// The controller also sets three reserved identity labels on every Job it creates, which jobTemplate
	// must not set itself (rejected at admission-adjacent validation, reported via the Ready condition):
	// promoter.argoproj.io/job-commit-status (this JobCommitStatus's name), promoter.argoproj.io/environment
	// (the environment branch), and promoter.argoproj.io/hydrated-sha (the SHA the Job was created for).
	// These identify which Job belongs to which environment/SHA; they are not intended as a stable
	// integration point for user workloads.
	//
	// In addition, every container and init container in jobTemplate.spec.template.spec receives four
	// plain (non-templated, pre-resolved) environment variables, appended to whatever the container
	// already defines: PROMOTER_JOB_SHA, PROMOTER_JOB_BRANCH, PROMOTER_JOB_PROMOTION_STRATEGY, and
	// PROMOTER_JOB_REPOSITORY.
	JobTemplate *v1.JobTemplateSpec `json:"jobTemplate,omitempty"`
}

// JobCommitStatusSpecApplyConfiguration constructs a declarative configuration of the JobCommitStatusSpec type for use with
// apply.
func JobCommitStatusSpec() *JobCommitStatusSpecApplyConfiguration {
	return &JobCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *JobCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithKey(value string) *JobCommitStatusSpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithReportOn sets the ReportOn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportOn field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithReportOn(value string) *JobCommitStatusSpecApplyConfiguration {
	b.ReportOn = &value
	return b
}

// WithDescriptionTemplate sets the DescriptionTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DescriptionTemplate field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithDescriptionTemplate(value string) *JobCommitStatusSpecApplyConfiguration {
	b.DescriptionTemplate = &value
	return b
}

// WithSuccess sets the Success field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Success field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithSuccess(value *JobCommitStatusSuccessSpecApplyConfiguration) *JobCommitStatusSpecApplyConfiguration {
	b.Success = value
	return b
}

// WithJobTemplate sets the JobTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobTemplate field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithJobTemplate(value v1.JobTemplateSpec) *JobCommitStatusSpecApplyConfiguration {
	b.JobTemplate = &value
	return b
}
