/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/batch/v1"
)

// JobCommitStatusSpecApplyConfiguration represents a declarative configuration of the JobCommitStatusSpec type for use
// with apply.
//
// JobCommitStatusSpec defines the desired state of JobCommitStatus.
//
// Applicable environments are NOT enumerated on this resource. Instead, the controller resolves
// them from the referenced PromotionStrategy the same way GitCommitStatus and WebRequestCommitStatus
// do: an environment is applicable when Key matches an entry in PromotionStrategy.Spec.ProposedCommitStatuses
// or Environment.ProposedCommitStatuses (reportOn=proposed), or PromotionStrategy.Spec.ActiveCommitStatuses
// or Environment.ActiveCommitStatuses (reportOn=active). The PromotionStrategy remains the single
// authoritative source for "which environments does this gate apply to".
type JobCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef is a reference to the promotion strategy that this commit status applies to.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Key is the gate name referenced in the PromotionStrategy's proposedCommitStatuses or activeCommitStatuses.
	// It is used as the commit status key and in status messages.
	// Must be lowercase alphanumeric with hyphens, 1–63 characters (pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$).
	Key *string `json:"key,omitempty"`
	// ReportOn specifies which commit SHA the Job is run against and the CommitStatus is reported on.
	// - "proposed" (default): the controller (re)creates the Job whenever the proposed hydrated SHA
	// changes for an applicable environment. Use this for pre-promotion gates (tests, evals, migrations
	// dry-runs) that must pass before the change is promoted.
	// - "active": the controller (re)creates the Job whenever the active hydrated SHA changes. Use this
	// for post-promotion checks that re-validate the environment after a promotion has landed.
	ReportOn *string `json:"reportOn,omitempty"`
	// DescriptionTemplate is the human-readable commit status description shown in the SCM provider
	// (GitHub, GitLab, etc.). Uses Go templates.
	//
	// Template variables (mirrors WebRequestCommitStatus's promotionstrategy-context variable set):
	// - {{ .Branch }}: the environment branch the Job was created for
	// - {{ .PromotionStrategy }}: the full PromotionStrategy spec and status
	// - {{ .JobCommitStatus }}: the full JobCommitStatus spec and status (snapshot from the previous reconcile)
	// - {{ .NamespaceMetadata.Labels }} / {{ .NamespaceMetadata.Annotations }}: labels/annotations of the namespace
	// - {{ .Job }}: the full child Job object once it has finished (nil while the Job is still running),
	// so the description can surface details such as {{ .Job.status.conditions }} or a container's
	// termination message.
	//
	// If not specified, defaults to empty string.
	DescriptionTemplate *string `json:"descriptionTemplate,omitempty"`
	// Success defines how to decide success/failure from the finished child Job.
	Success *JobCommitStatusSuccessSpecApplyConfiguration `json:"success,omitempty"`
	// JobTemplate is a standard batch/v1 Job template, embedded verbatim. The controller does not inject
	// defaults into the Job spec itself — native Job mechanics carry their own weight:
	// backoffLimit            -> retry semantics
	// activeDeadlineSeconds   -> timeout
	// ttlSecondsAfterFinished -> cleanup (a reasonable suggestion is 24h; not defaulted by the controller)
	//
	// Templating (Go templates, same variables as DescriptionTemplate) is supported ONLY in
	// jobTemplate.metadata.labels and jobTemplate.metadata.annotations; the rest of the Job spec is used
	// as-is. The controller also stamps promoter.argoproj.io/branch, promoter.argoproj.io/dry-sha, and
	// promoter.argoproj.io/hydrated-sha labels onto the created Job (and, transitively, its Pods), so
	// they're available to the running container via the downward API.
	JobTemplate *v1.JobTemplateSpec `json:"jobTemplate,omitempty"`
}

// JobCommitStatusSpecApplyConfiguration constructs a declarative configuration of the JobCommitStatusSpec type for use with
// apply.
func JobCommitStatusSpec() *JobCommitStatusSpecApplyConfiguration {
	return &JobCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *JobCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithKey(value string) *JobCommitStatusSpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithReportOn sets the ReportOn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportOn field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithReportOn(value string) *JobCommitStatusSpecApplyConfiguration {
	b.ReportOn = &value
	return b
}

// WithDescriptionTemplate sets the DescriptionTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DescriptionTemplate field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithDescriptionTemplate(value string) *JobCommitStatusSpecApplyConfiguration {
	b.DescriptionTemplate = &value
	return b
}

// WithSuccess sets the Success field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Success field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithSuccess(value *JobCommitStatusSuccessSpecApplyConfiguration) *JobCommitStatusSpecApplyConfiguration {
	b.Success = value
	return b
}

// WithJobTemplate sets the JobTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobTemplate field is set to the value of the last call.
func (b *JobCommitStatusSpecApplyConfiguration) WithJobTemplate(value v1.JobTemplateSpec) *JobCommitStatusSpecApplyConfiguration {
	b.JobTemplate = &value
	return b
}
