/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// JobCommitStatusEnvironmentStatusApplyConfiguration represents a declarative configuration of the JobCommitStatusEnvironmentStatus type for use
// with apply.
//
// JobCommitStatusEnvironmentStatus defines the observed Job/gate status for a specific environment.
type JobCommitStatusEnvironmentStatusApplyConfiguration struct {
	// Branch is the environment branch name being gated.
	Branch *string `json:"branch,omitempty"`
	// Sha is the hydrated commit SHA (proposed or active, per spec.reportOn) that the current or most
	// recent Job was created for.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	Sha *string `json:"sha,omitempty"`
	// JobRef references the child Job created for Sha. The Job always lives in the JobCommitStatus's own
	// namespace.
	JobRef *JobCommitStatusJobReferenceApplyConfiguration `json:"jobRef,omitempty"`
	// Phase represents the current phase of the gate for this environment.
	// - "pending": the Job has been created but has not finished, or no Job has been created yet for Sha
	// - "success": the Job finished and success.when.expression evaluated to true
	// - "failure": the Job finished and success.when.expression evaluated to false, or the Job itself
	// failed (for example activeDeadlineSeconds was exceeded or backoffLimit was reached)
	Phase *apiv1alpha1.CommitStatusPhase `json:"phase,omitempty"`
	// StartedAt is when the current/most recent Job was created.
	StartedAt *v1.Time `json:"startedAt,omitempty"`
	// FinishedAt is when the current/most recent Job reached a terminal state (Complete or Failed).
	// This is taken from the terminal condition's own LastTransitionTime (not the reconcile time),
	// so it stays stable across reconciles as long as the Job's conditions don't change.
	FinishedAt *v1.Time `json:"finishedAt,omitempty"`
	// Reason is a short, machine-readable reason for the current Phase. While terminal, it mirrors
	// the finished Job's Complete/Failed condition reason (for example "DeadlineExceeded",
	// "BackoffLimitExceeded"); otherwise it is a controller-synthesized reason (for example
	// "JobRunning", "JobCreateFailed").
	Reason *string `json:"reason,omitempty"`
}

// JobCommitStatusEnvironmentStatusApplyConfiguration constructs a declarative configuration of the JobCommitStatusEnvironmentStatus type for use with
// apply.
func JobCommitStatusEnvironmentStatus() *JobCommitStatusEnvironmentStatusApplyConfiguration {
	return &JobCommitStatusEnvironmentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *JobCommitStatusEnvironmentStatusApplyConfiguration) WithBranch(value string) *JobCommitStatusEnvironmentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithSha sets the Sha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sha field is set to the value of the last call.
func (b *JobCommitStatusEnvironmentStatusApplyConfiguration) WithSha(value string) *JobCommitStatusEnvironmentStatusApplyConfiguration {
	b.Sha = &value
	return b
}

// WithJobRef sets the JobRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobRef field is set to the value of the last call.
func (b *JobCommitStatusEnvironmentStatusApplyConfiguration) WithJobRef(value *JobCommitStatusJobReferenceApplyConfiguration) *JobCommitStatusEnvironmentStatusApplyConfiguration {
	b.JobRef = value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *JobCommitStatusEnvironmentStatusApplyConfiguration) WithPhase(value apiv1alpha1.CommitStatusPhase) *JobCommitStatusEnvironmentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *JobCommitStatusEnvironmentStatusApplyConfiguration) WithStartedAt(value v1.Time) *JobCommitStatusEnvironmentStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithFinishedAt sets the FinishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FinishedAt field is set to the value of the last call.
func (b *JobCommitStatusEnvironmentStatusApplyConfiguration) WithFinishedAt(value v1.Time) *JobCommitStatusEnvironmentStatusApplyConfiguration {
	b.FinishedAt = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *JobCommitStatusEnvironmentStatusApplyConfiguration) WithReason(value string) *JobCommitStatusEnvironmentStatusApplyConfiguration {
	b.Reason = &value
	return b
}
